steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ailbee/enterprise-hub:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ailbee/enterprise-hub:latest']
options:
  logging: 'CLOUD_LOGGING_ONLY'
