steps:
  # Запускаем сборку по вашему Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/ailbee/cloud-run-source-deploy/ailbee-enterprise/ailbee-enterprise-hub:$COMMIT_SHA',
      '-f', 'Dockerfile',
      '.'
    ]

# Напрямую приказываем системе использовать только Cloud Logging (Вариант С из ошибки!)
options:
  logging: CLOUD_LOGGING_ONLY
