steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'ailbee-enterprise-hub',
      '--source', 'backend',
      '--repo', 'us-central1-docker.pkg.dev/ailbee/ailbee-enterprise',
      '--region', 'us-central1',
      '--project', 'ailbee',
      '--no-traffic'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
