steps:
  # Шаг сборки контейнера
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/ailbee/ailbee-enterprise/gemma-4-standard:latest',
      '-f', 'Dockerfile',
      '.'
    ]

# КРИТИЧЕСКИЙ БЛОК: Говорим Google Cloud принудительно сохранить образ в Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/ailbee/ailbee-enterprise/gemma-4-standard:latest'

options:
  logging: CLOUD_LOGGING_ONLY
