name: Deploy Web to Firebase Hosting

on:
  push:
    branches:
      - flutterflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Resolve Dependency Conflicts
        run: |
          echo "" >> pubspec.yaml
          echo "dependency_overrides:" >> pubspec.yaml
          echo "  intl: ^0.20.3" >> pubspec.yaml

      - name: Build Web App
        run: |
          flutter pub get
          flutter build web --release --no-tree-shake-icons

      - name: Create firebase.json
        run: |
          echo '{"hosting":{"public":"build/web","ignore":["firebase.json","**/.*","**/node_modules/**"],"rewrites":[{"source":"**","destination":"/index.html"}]}}' > firebase.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AILBEE }}'
          channelId: live
          projectId: ailbee
